package com.kd.distribute.model;

import java.math.BigDecimal;
import java.util.Date;

public class KdOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order.id
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order.order_status
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order.receiver_name
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order.receiver_mobile
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private String receiverMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order.order_amount
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private BigDecimal orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order.time_created
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private Date timeCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order.time_modified
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private Date timeModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order.create_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order.update_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order.id
     *
     * @return the value of kd_order.id
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order.id
     *
     * @param id the value for kd_order.id
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order.order_status
     *
     * @return the value of kd_order.order_status
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order.order_status
     *
     * @param orderStatus the value for kd_order.order_status
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order.receiver_name
     *
     * @return the value of kd_order.receiver_name
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order.receiver_name
     *
     * @param receiverName the value for kd_order.receiver_name
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order.receiver_mobile
     *
     * @return the value of kd_order.receiver_mobile
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order.receiver_mobile
     *
     * @param receiverMobile the value for kd_order.receiver_mobile
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order.order_amount
     *
     * @return the value of kd_order.order_amount
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order.order_amount
     *
     * @param orderAmount the value for kd_order.order_amount
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order.time_created
     *
     * @return the value of kd_order.time_created
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public Date getTimeCreated() {
        return timeCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order.time_created
     *
     * @param timeCreated the value for kd_order.time_created
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setTimeCreated(Date timeCreated) {
        this.timeCreated = timeCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order.time_modified
     *
     * @return the value of kd_order.time_modified
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public Date getTimeModified() {
        return timeModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order.time_modified
     *
     * @param timeModified the value for kd_order.time_modified
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setTimeModified(Date timeModified) {
        this.timeModified = timeModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order.create_user
     *
     * @return the value of kd_order.create_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order.create_user
     *
     * @param createUser the value for kd_order.create_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order.update_user
     *
     * @return the value of kd_order.update_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order.update_user
     *
     * @param updateUser the value for kd_order.update_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}