package com.kd.distribute.model;

import java.math.BigDecimal;
import java.util.Date;

public class KdOrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order_item.id
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order_item.order_id
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order_item.product_id
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order_item.purchase_price
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private BigDecimal purchasePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order_item.purchase_num
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private Integer purchaseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order_item.time_created
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private Date timeCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order_item.time_modified
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private Date timeModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order_item.create_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_order_item.update_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order_item.id
     *
     * @return the value of kd_order_item.id
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order_item.id
     *
     * @param id the value for kd_order_item.id
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order_item.order_id
     *
     * @return the value of kd_order_item.order_id
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order_item.order_id
     *
     * @param orderId the value for kd_order_item.order_id
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order_item.product_id
     *
     * @return the value of kd_order_item.product_id
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order_item.product_id
     *
     * @param productId the value for kd_order_item.product_id
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order_item.purchase_price
     *
     * @return the value of kd_order_item.purchase_price
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public BigDecimal getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order_item.purchase_price
     *
     * @param purchasePrice the value for kd_order_item.purchase_price
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setPurchasePrice(BigDecimal purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order_item.purchase_num
     *
     * @return the value of kd_order_item.purchase_num
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public Integer getPurchaseNum() {
        return purchaseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order_item.purchase_num
     *
     * @param purchaseNum the value for kd_order_item.purchase_num
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setPurchaseNum(Integer purchaseNum) {
        this.purchaseNum = purchaseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order_item.time_created
     *
     * @return the value of kd_order_item.time_created
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public Date getTimeCreated() {
        return timeCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order_item.time_created
     *
     * @param timeCreated the value for kd_order_item.time_created
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setTimeCreated(Date timeCreated) {
        this.timeCreated = timeCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order_item.time_modified
     *
     * @return the value of kd_order_item.time_modified
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public Date getTimeModified() {
        return timeModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order_item.time_modified
     *
     * @param timeModified the value for kd_order_item.time_modified
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setTimeModified(Date timeModified) {
        this.timeModified = timeModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order_item.create_user
     *
     * @return the value of kd_order_item.create_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order_item.create_user
     *
     * @param createUser the value for kd_order_item.create_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_order_item.update_user
     *
     * @return the value of kd_order_item.update_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_order_item.update_user
     *
     * @param updateUser the value for kd_order_item.update_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}