package com.kd.distribute.model;

import java.math.BigDecimal;
import java.util.Date;

public class KdProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_product.id
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_product.product_name
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_product.price
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_product.count
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_product.product_desc
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private String productDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_product.time_created
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private Date timeCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_product.time_modified
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private Date timeModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_product.create_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_product.update_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_product.id
     *
     * @return the value of kd_product.id
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_product.id
     *
     * @param id the value for kd_product.id
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_product.product_name
     *
     * @return the value of kd_product.product_name
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_product.product_name
     *
     * @param productName the value for kd_product.product_name
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_product.price
     *
     * @return the value of kd_product.price
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_product.price
     *
     * @param price the value for kd_product.price
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_product.count
     *
     * @return the value of kd_product.count
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_product.count
     *
     * @param count the value for kd_product.count
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_product.product_desc
     *
     * @return the value of kd_product.product_desc
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_product.product_desc
     *
     * @param productDesc the value for kd_product.product_desc
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_product.time_created
     *
     * @return the value of kd_product.time_created
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public Date getTimeCreated() {
        return timeCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_product.time_created
     *
     * @param timeCreated the value for kd_product.time_created
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setTimeCreated(Date timeCreated) {
        this.timeCreated = timeCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_product.time_modified
     *
     * @return the value of kd_product.time_modified
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public Date getTimeModified() {
        return timeModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_product.time_modified
     *
     * @param timeModified the value for kd_product.time_modified
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setTimeModified(Date timeModified) {
        this.timeModified = timeModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_product.create_user
     *
     * @return the value of kd_product.create_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_product.create_user
     *
     * @param createUser the value for kd_product.create_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_product.update_user
     *
     * @return the value of kd_product.update_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_product.update_user
     *
     * @param updateUser the value for kd_product.update_user
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}