package com.kd.distribute.dao;

import com.kd.distribute.model.KdOrder;
import com.kd.distribute.model.KdOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KdOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    long countByExample(KdOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    int deleteByExample(KdOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    int insert(KdOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    int insertSelective(KdOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    List<KdOrder> selectByExample(KdOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    KdOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") KdOrder record, @Param("example") KdOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    int updateByExample(@Param("record") KdOrder record, @Param("example") KdOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    int updateByPrimaryKeySelective(KdOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    int updateByPrimaryKey(KdOrder record);
}