package com.kd.distribute.dao;

import com.kd.distribute.model.KdOrderItem;
import com.kd.distribute.model.KdOrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KdOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order_item
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    long countByExample(KdOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order_item
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    int deleteByExample(KdOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order_item
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order_item
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    int insert(KdOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order_item
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    int insertSelective(KdOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order_item
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    List<KdOrderItem> selectByExample(KdOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order_item
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    KdOrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order_item
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") KdOrderItem record, @Param("example") KdOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order_item
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    int updateByExample(@Param("record") KdOrderItem record, @Param("example") KdOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order_item
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    int updateByPrimaryKeySelective(KdOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_order_item
     *
     * @mbg.generated Fri Dec 25 22:56:30 CST 2020
     */
    int updateByPrimaryKey(KdOrderItem record);
}